name: small
version: 0.1.0.0
license: BSD-3-Clause
author: mu-fomega contributors
maintainer: mu-fomega contributors
copyright: "2026"
tested-with: GHC ==9.14.*

dependencies:
  - base >= 4.8 && < 5  # need 4.8 for Numeric.Natural
  - array  # for alex
  - containers # Data.Set for Megaparsec
  - megaparsec
  - mtl  # MonadState for Megaparsec
  - vector # We use Vector of tokens as input for Megaparsec.

ghc-options:
  - -Wall

default-extensions:
  - DerivingStrategies
  - LambdaCase
  - NamedFieldPuns
  - NoFieldSelectors
  - OverloadedRecordDot
  - OverloadedStrings
  - RecordWildCards
  - StrictData

library:
  source-dirs: src
  exposed-modules:
    - Small
    - Syntax
    - LexerDefs
    - Lexer
    - Parser
  build-tools:
    - alex

tests:
  small-test:
    main: Spec.hs
    source-dirs: test
    build-tools:
      - hspec-discover
    dependencies:
      - small
      - hspec
      - hspec-discover
