name: small
version: 0.1.0.0
license: BSD-3-Clause
author: mu-fomega contributors
maintainer: mu-fomega contributors
copyright: "2026"
tested-with: GHC ==9.14.*

dependencies:
  - base >= 4.8 && < 5  # need 4.8 for Numeric.Natural
  - array  # for alex
  - megaparsec
  - vector

ghc-options:
  - -Wall

default-extensions:
  - OverloadedStrings
  - StrictData
  - LambdaCase
  - DerivingStrategies
  - OverloadedRecordDot
  - RecordWildCards
  - NamedFieldPuns

library:
  source-dirs: src
  exposed-modules:
    - Small
    - Syntax
    - Lexer
  build-tools:
    - alex

tests:
  small-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - small
      - hspec
